apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: sna
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: sna
    app.kubernetes.io/part-of: sna
  name: sna
  namespace: sna
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: sna
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: sna
    spec:
      containers:
      - image: quay.io/jduimovich0/sna
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        name: container-image
        ports:
        - containerPort: 8080
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          tcpSocket:
            port: 8080
        resources:
          requests:
            cpu: 50m
            memory: 512Mi
status: {}
